
services:
  server:
   image: "nginx:stable-alpine"
   ports:
     - "8000:80"
   volumes: 
    - "./src:/var/www/html"
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
   depends_on:
      - php
      - mysql

  php:
    build:
     context : ./DockerFiles  # the folder where to find this file in
     dockerfile: php.dockerfile  # this is how I let compose know about which docker file im running for this service 
    volumes : 
      - "./src:/var/www/html" # mounting our src from our machine to the var/www/html folder in our container , note we adding the :delegated to the end , this is for performance

  mysql:
    image: "mysql:5.7"
    env_file:
      - ./env/mysql.env

  composer:
    build: 
      context: ./DockerFiles
      dockerfile: composer.dockerfile
    
    volumes:
        - "./src:/var/www/html"

#  artisan:
#  npm:

